### ISSUE TITLE
cocoapods linking error

### ISSUE THREAD

**Issue by brenthargrave** [workshop/struct#109]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version
2.0.1

## Spec version
spec('2.0.0')

## Which type of spec are you using?

- [ ] project.yml
- [ ] project.json
- [x] Specfile

## Context

Integrating cocoapods per the latest docs and cocoapods wiki page:
https://github.com/workshop/struct/wiki/Specfile-format:-v2.0#cocoapods
https://github.com/workshop/struct/wiki/Integrating-with-Cocoapods

My app's source is published here, on the `struct`  branch:
https://github.com/brenthargrave/tba-ios/tree/struct

## Reproduction steps

`git clone git@github.com:brenthargrave/tba-ios.git`
`cd tba-ios`
`git checkout struct`
`bundle install`
`bundle exec pod install`
`struct generate`
`open project.xcodeproj`

Build the app.

## Expected result

Clean build.

## Actual result

Build fails on linking cocoapods:    
```
ld: warning: directory not found for option '-F/Users/jamescallmebrent/Library/Developer/Xcode/DerivedData/project-binqompdcglaqcdtndqkoquvtkwk/Build/Products/debug-iphonesimulator/Alamofire'
ld: framework not found Alamofire
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by lyptt** [comment]
Hi @brenthargrave, thanks for filing this issue. Have you run pod install before generating the project? If you miss this step then struct won't be able to add the frameworks to your build phases. 

You can also make sure this happens by using a [pre-generate hook](https://github.com/workshop/struct/wiki/Specfile-format%3A-v2.0#lifecycle-hooks).

**Comment by lyptt** [comment]
Hi @brenthargrave, I found the issue. Due to the way Cocoapods works, they expect the standard 'Debug' and 'Release' project configuration profiles to be used, rather than struct's default 'debug' and 'release'.

I've updated the wiki with this in mind, and reproduced the steps below.

----------

You will also need to use the default project configuration names when making use of Cocoapods, as Cocoapods itself expects this. If you fail to do this, you'll find yourself getting linker errors. This can be done as follows:

**YAML**

```yaml
configurations:
  Debug:
    type: debug
  Release:
    type: release
```

**Specfile**

```ruby
spec('2.0.0') do
  configuration('Debug') do
    type :debug
  end
  configuration('Release') do
    type :release
  end
```
