### ISSUE TITLE
Target type warnings (Add support for tvOS)

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#121]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

[2.1.0]

## Spec version

[2.1.0]

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

When generating a spec with a `tv-app-extension` target, there are 6 identical warnings saying:
```
Warning: unrecognised project configuration profile 'tv-app-extension'. Ignoring...
```
I guess this is just Struct not being able to find a relevant profile to apply for build settings, but should it be a user facing warning? As an aside it's interesting that this gets printed 6 times even though there's only 1 relevant target. Maybe highlights some redundant code paths?

**Comment by lyptt** [comment]
Hi @yonaskolb, thanks for filing this issue. Yes, right now for tvOS only the application target is supported. tvOS is the only platform left to support before Struct supports every platform, I'm hoping to get this in for the next release.

Fundamentally as you've noticed the main thing we need to do to support new platforms is add new configuration profiles, however there may be additional work needed to get the projects building correctly in Xcode. Often Apple sneaks in special build phases that we need to reverse engineer and add ourselves, as is the case with watchOS.

As we expand our support for all of Apple's target types, this warning will become a rarer sight, however I think it's still valuable for an end user to see it. Otherwise we may get into situations where Apple changes a target type's name, or adds new ones behind the scenes when a platform gets a major SDK update. In this scenario we'll need to know that these target types need to be added to Struct.

**Comment by yonaskolb** [comment]
For getting these profile settings, I could imagine something fancy like an automated process that creates a new XCode targets using AppleScript or something, and then reading the settings from that project to create profiles 🤖 😄

**Comment by lyptt** [comment]
Yeah it could definitely be achievable - my process is usually as follows:

- Create the target in Xcode with an easily identifiable name
- Open the pbjproj file, search for the target's configuration block
- Copy out all of the settings for Debug & Release, strip out any settings covered by platform / base configurations
- Save these into a target profile following the correct naming convention
- Test!

I may actually have a go at automating this. It sounds fun! 🚀
