### ISSUE TITLE
Deterministic generation

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#125]
It would be great if the generated Xcode project was deterministically generated, meaning if it was generated with the same spec, the output would be the same.
This would aid in diffs (even though I know the aim of Struct is not to have the xcode project checked in), but more importantly would stop Xcode from reloading a project even though there are no real changes.

I'm not sure if you have any control over this, if you're using cocoapods' `xcodeproject`? 
There was a pull request there though that seemed to add this functionality https://github.com/CocoaPods/Xcodeproj/pull/283

**Comment by lyptt** [comment]
Ah that's very interesting! I missed this when I looked at Xcodeproj's documentation. One of the bigger caveats to Struct's watch mode is that occasionally Xcode will enter a broken state when it reloads the project due to the UUIDs changing, and one of its code paths not being able to handle it.

If the UUIDs are deterministic, that should help solve the issue. I'll definitely look into this!
