### ISSUE TITLE
Add flags to source code

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#41]
In Xcake we have a request to support addinga flag to a certain compiled file, I think we should look at adding this to Struct.

**Comment by lyptt** [comment]
Hi @jcampbell05, what flags would you usually need to add? `-W` and the like?

**Comment by jcampbell05** [comment]
@lyptt things such as that, there are things you can apply like `ARC` that change how a file is compiled. I realise that it's deprecated but I know people use it.

Maybe this is something better handled by `.xcconfig`.

Personally I never use the flags.

**Comment by lyptt** [comment]
Hi @jcampbell05 yes I agree, personally I think this is a task that could be achieved in other means. If this is possible to achieve without a complex DSL extension then I would highly prefer it. Then this would be more of a documentation task than anything else.

**Comment by lyptt** [comment]
My personal opinion on this, is that struct as a tool should absolutely continue to support Objective-C functionality, but adding additional DSL for all of the complexities and edge cases in Objective-C projects isn't really ideal for this tool.

If we can achieve this in a way that is at best automatic, or implicit in nature, without the user having to do any additional work, then that's the best possible outcome. Struct is all about applying sensible defaults whenever possible so you don't have to consider the minutea of Xcode projects.

**Comment by jcampbell05** [comment]
@lyptt Completely agree in Xcake I took the same approach, out of the box with sensible defaults but allowed just enougth flexibility to fit your project.

So I did a bit of digging and I don't think it's possible to do with xcconfig but I have a simple solution. We could add a flag modifier like so:

```
include:
- **/*.*
-ineedarc.c  //Would be ineedarc.c, :flags: -fno-objc in DSL
    - flags: -fno-objc
- hey.swift
    -flags: I'm not sure what swift flags there are but xcode supports them
```

This was the approach I was thinking of doing in Xcake.

**Comment by lyptt** [comment]
Hi @jcampbell05, this definitely could be an option, however it would significantly complicate parsing and project generation.

Another option is to have an additional DSL to apply changes matching file globs, e.g.:

```yaml
source_options:
  src/**/ineedarc.c: -fno-obj-c -W
```

**Comment by jcampbell05** [comment]
@lyptt Yes that sounds perfect, do you know where exactly in the code we should add this ?

**Comment by lyptt** [comment]
Yup, so first off this would be a brand new spec version - 1.3.0. So there's a few steps involved in building this out:

- Duplicate the latest StructCore::SpecParserXXX as StructCore::Specparser13X in `lib/spec/parser`
- Update the new class to be properly named as Specparser13X, update its `:can_parse_version` method to properly check for the new spec version
- Duplicate the tests in `spec/unit' for the latest spec file format, and duplicate the support files for these in `spec/support/` for the new version
- In all of the support files, update the version number to be 1.3.0 to ensure they're parseable by the new parser
- In all of the new unit tests, update the version number to be 1.3.0 and the Parser class to be the new parser class

You would need to perform similar changes for the SpecXXXDSL classes in `lib/spec/builder/spec_builder_12X` (this is the Ruby DSL).

With this sorted, you can then go about adding new functionality to the new spec version in your new SpecParser and SpecXXXDSL classes. By performing this process we're making an absolute guarantee that existing spec files continue to parse as they always have. This prevents a lot of regression scenarios we'd otherwise encounter.

**Comment by jcampbell05** [comment]
@lyptt this all sounds good, I'll look into this. Good point about the regressions, one of the mistakes I made with Xcake is not versioning the specs although I did the usual semver guarantees (Like Cocoapods) but Projects are more complex so usually people don't migrate as fast.

**Comment by lyptt** [comment]
Sure thing! If you need any advice, hit me up on the gitter room and I can help you with the process. It's fairly involved, but it's best for us to have the pain rather than the end users!

Generally we only watch out for minor versions, however we've started checking patch versions too on one new feature. I'm still investigating ways to make this more seamless.
