### ISSUE TITLE
Break Struct's files into smaller modules

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#60]
I've noticed that a lot of Struct is based in very large single files. In Xcake I broke these up into individual generators that focused on very small tasks (i.e just making a target).

This made it much easier to test, understand and control what happens and when.
Look how small the Generator for adding libraries is :) 
https://github.com/jcampbell05/xcake/blob/master/lib/xcake/generator/target_library_generator.rb

It should also make it very easy for new developers to get involved :) I'm not sure how this will work with the project recreation and other commands of Struct.

**Comment by lyptt** [comment]
Yup I agree this should be done - two main files need refactoring, migrator.rb and xcodeproj_writer.rb.

Before this happens we should finish adding a full suite of integration tests to make sure we don't break project generation.

**Comment by jcampbell05** [comment]
Yeah, makes sense as we are about to play with CircleCI as well, what sort of tests you thinking of ? 

The way I broke Xcake up was by BDD-ing it as I found that it was so hard to test I had to break it up.

Sidenote: I guess for the migration we could make the generator concept in Xcake bidirectional, so it knows how to go from DSL -> Project and back again :)

**Comment by lyptt** [comment]
@jcampbell05 So my solution for it to start is to just make sure as many branches are covered in the writer / migrator as possible, but treat it as a black box.

This would be done by feeding these classes spec files (writer) / xcode projects (migrator) that include different bits of functionality so that we know each spec file feature can make its way into a buildable Xcode project.

For project generation it technically is bidirectional - if you check the SpecWriter tests, we actually read in a spec file, write it out, read it in again and compare the object structures between the original and the new one to verify nothing's missing. It's fairly exhaustive 😄

**Comment by jcampbell05** [comment]
@lyptt  awesome I'll take a look at these to gain a deeper understand and to see if I can start writing tests since that will help me to get to grips with things :) 

:) for the bidirectional stuff I was meaning more how we can break it down. But thats a pretty ingenious way of doing it :)
