### ISSUE TITLE
Internalise configuration profiles

### ISSUE THREAD

**Issue by lyptt** [workshop/struct#67]
Currently when configuring projects and targets, you have to specify configuration profiles matching your target type / overall project.

As we can infer these details quite easily, we should internalise profiles and make this an implementation detail, to reduce configuration burden on our users.

**Comment by jcampbell05** [comment]
This will be useful for cook which I've had to pause development on for the meantime until we have this :) https://github.com/jcampbell05/cook

**Comment by jcampbell05** [comment]
Looked into this it seems the only thing that doesn't infer profiles are configurations at the project level.

I also discovered we don't have a profile for iOS unit tests vs Mac unit tests as they have differences.

Once I've got the configurations to infer then in future I think we could simplify the code a sort of our arch discussion since I wasn't sure to put the code

**Comment by lyptt** [comment]
Fixed in 2.0.0.
